name: Build

on:
  push:
    paths-ignore:
      - '**.md'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore tools
        run: dotnet tool restore

      - name: Build
        run: dotnet build ShipLobby/ShipLobby.csproj -c Release
